### ISSUE TITLE
[!] No podspec found for `flutter_better_camera` in `.symlinks/plugins/flutter_better_camera/ios`

### ISSUE THREAD

**Issue by 120011676** [Lightsnap/flutter_better_camera#5]
[!] No podspec found for `flutter_better_camera` in `.symlinks/plugins/flutter_better_camera/ios`

**Comment by roxifas** [comment]
This is already fixed in master, to get the fix right now you can replace the dependency in your `pubspec.yaml` with this:
```
  flutter_better_camera:
    git:
      url: https://github.com/Lightsnap/flutter_better_camera.git
      ref: 7a654c3994509ec37012fcf5bafd54a0049b1026
```
